config/routes.rb
Rails.application.routes.draw do
  get 'recommendations/index'
  get 'recommendations/create'
  get 'recommendations/destroy'
  devise_for :users
  root to: 'pages#home'
  resources :movies, only: [:index, :show] do
    resources :movie_selections, only: [:create]
    resources :recommendations, only: [:create]
  end

  resources :friends, only: [:index, :destroy]
  resources :movie_selections, only: [:index, :update]
  get '/movie_selections/watched', to: 'movie_selections#watched', as: 'watched_movie_selections'
  get '/movie_selections/favourites', to: 'movie_selections#favourites', as: 'favourites_movie_selections'
  resources :users, only: [:show, :index] do
    resources :friends, only: [:create]
  end
  resources :recommendations, only: [:index, :destroy]


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :recommendations, only: [ :destroy ] do
        member do
          get :watch
        end
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :friend, class_name: "User"
  belongs_to :user
end

app/models/movie.rb
class Movie < ApplicationRecord
  extend Enumerize

  enumerize :platform, in: [:netflix, :amazon, :disney_plus, :apple_tv_plus, :youtube, :rakuten, :now], predicates: true, scope: true

  has_one_attached :poster
end

app/models/movie_selection.rb
class MovieSelection < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  belongs_to :recommendee, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :movie_selections
  has_many :movies, through: :movie_selections
  has_many :friends
  has_many :friend_users, through: :friends, source: :friend
  has_many :other_friends, class_name: "Friend", foreign_key: "friend_id"
  has_many :other_friend_users, through: :other_friends, source: :user
  has_many :recommendations
  has_many :movie_recommendations, through: :recommendations, source: :movie
  has_many :recommended, class_name: "Recommendation", foreign_key: :recommendee_id
  has_many :recommended_movies, through: :recommended, source: :movie
  has_one_attached :photo

  def all_friends
    friends + other_friends
  end

  def all_friend_people
    friend_users + other_friend_users
  end

  def friends?(user)
    all_friends.pluck(:user_id, :friend_id).flatten.include?(user.id)
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API

end

app/controllers/api/v1/recommendations_controller.rb
class Api::V1::RecommendationsController < Api::V1::BaseController
  def watch
    @recommendation = Recommendation.find(params[:id])
    MovieSelection.create(user: @recommendation.recommendee, movie: @recommendation.movie, watched: false)
    @recommendation.destroy
    render json: { status: "success" }
  end

  def destroy
    @recommendation = Recommendation.find(params[:id])
    @recommendation.destroy
    render json: { status: "success" }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :bio, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :bio, :photo])
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends = all_friends
  end

  def create
    @friend = Friend.new(friend: User.find(params[:friend].to_i))
    @friend.user = current_user
    @friend.save
    redirect_back fallback_location: request.referrer
  end

  def destroy
    @friend = Friend.find(params[:id])
    @friend.destroy
    redirect_back fallback_location: request.referrer
  end

  private

  def friend_params
    params.require(:friend).permit(:movie_id, :friend_id)
  end
end

app/controllers/movie_selections_controller.rb
class MovieSelectionsController < ApplicationController
  def index
    @movie_selections = current_user.movie_selections.where(watched: false)
  end

  def watched
    @movie_selections = current_user.movie_selections.where(watched: true)
  end

  def favourites
    @movie_selections = current_user.movie_selections.where(favourite: true)

  end

  def update
    @movie_selection = MovieSelection.find(params[:id])
    @movie_selection.toggle!(params[:attribute])
    sleep(1)
    redirect_to redirection_path(params[:attribute])
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @movie_selection = MovieSelection.new(user: current_user, movie: @movie)

    if @movie_selection.save
      redirect_to movie_selections_path, notice: "Yay! 🎉 this movie has been added"
    else
      redirect_to movies_path
    end
  end

  private

  def redirection_path(attribute)
    case attribute
    when "watched" then watched_movie_selections_path
    when "favourite" then favourites_movie_selections_path
    end
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if params.has_key?("platform")
      @movies = Movie.with_platform(params["platform"])
    elsif params.has_key?("query")
      @movies = Movie.where("title ILIKE ?", "%#{params[:query]}%")
    else
      @movies = Movie.all
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @recommendation = Recommendation.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def index
    @recomendations_i_made = current_user.recomendations
    @recomendations_made_to_me = current_user.recommended
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @recommendation = Recommendation.new(recommendation_parmams)
    @recommendation.user = current_user
    @recommendation.movie = @movie
    @recommendation.save
    flash[:notice] = "Movie recommended to #{@recommendation.recommendee.first_name}!"

    redirect_back fallback_location: request.referrer
  end

  def destroy
  end

  def recommendation_parmams
    params.require(:recommendation).permit(:recommendee_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @friends = current_user.all_friend_people
    @ids = [current_user.id] + @friends.map{|r| r.id}
    if params[:query]
      @users = User.where.not(id: @ids).where("first_name ILIKE ?", "%#{params[:query]}%")
    else
      @users = User.where.not(id: @ids)
    end
  end

  def show
    @user = User.find(params[:id])
    if params[:query]
      @users = User.where.not(id: current_user.id).where("first_name ILIKE ?", "%#{params[:query]}%")
    else
      @users = User.where.not(id: current_user.id)
    end

    @recommended_movies = @user.recommendations.order(created_at: :desc).first(4)
    @suggested_movies = @user.recommended.order(created_at: :desc).first(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["FELLINI"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["Discover and recommend movies on all your favourite streaming platforms"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/friends/index.html.erb
<div class="container">
  <h1>Your friends...</h1>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FELLINI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div style= "min-height:calc(100vh - 116px)">
    <%= yield %>
    </div>

      <!-- footer -->
    </div>
      <div class="footer <%= "no-margin-top" if current_page?(root_path) %>">
        <div class="footer-links">
          <a target="_blank" href="https://giphy.com/gifs/memecandy-LmNwrBhejkK9EFP504"><i class="fab fa-facebook"></i></a>
          <a target="_blank" href="https://giphy.com/gifs/memecandy-hrRJ41JB2zlgZiYcCw"><i class="fab fa-twitter"></i></a>
          <a target="_blank" href="https://giphy.com/gifs/cat-kitten-computer-3oKIPnAiaMCws8nOsE"><i class="fab fa-instagram"></i></a>
        </div>
        <div class="footer-copyright">
          <i class="fas fa-heart"></i>  Borja, Nick and Beatriz <i class="fas fa-heart"></i>
        </div>
      </div>
      <!-- end of footer -->

  </body>
</html>

app/views/movie_selections/favorites.html.erb
<div class="container">
  <!-- <h1>FAVOURITES...</h1> -->
  <div class="row justify-content-center">
    <div class="div.col-md-6">
      <%= link_to 'Watchlist', movie_selections_path, class: "btn m-3 " %>
      <%= link_to  'Already watched', watched_movie_selections_path, class: "btn m-3 active-tab" %>
      <%= link_to  'Favourites', watched_movie_selections_path, class: "btn m-3" %>
    </div>
  </div>
</div>


<div class= "smallcard-space">
  <div class="smallcards">

    <% @movie_selections.each do |movie_selection| %>


      <div class="smallcard-category relative" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path movie_selection.movie.poster.key %>)">

        <div class="absolutestar">
        <%= link_to movie_selection_path(movie_selection),attribute: :favourite), method: :put do %>
        <div class="HeartAnimation iconstyle"></div>
        <%# end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/movie_selections/favourites.html.erb
<div class="container">
  <!-- <h1>FAVOURITES...</h1> -->
  <div class="row justify-content-center">
    <div class="div.col-md-6">
      <%= link_to 'Watchlist', movie_selections_path, class: "btn m-3 " %>
      <%= link_to  'Already watched', watched_movie_selections_path, class: "btn m-3 " %>
      <%= link_to  'Favourites', favourites_movie_selections_path, class: "btn m-3 active-tab" %>
    </div>
  </div>
</div>


<div class= "smallcard-space">
  <div class="smallcards">

    <% @movie_selections.each do |movie_selection| %>

      <%= link_to movie_path(movie_selection.movie) do  %>
        <div class="smallcard-category relative" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path movie_selection.movie.poster.key %>)">
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/movie_selections/index.html.erb
<div class="container">
  <!-- <h1>Watchlist...</h1> -->
  <div class="row justify-content-center">
    <div class="div.col-md-6">
      <%= link_to  'Watchlist', movie_selections_path, class: "btn m-3 active-tab" %>
      <%= link_to  'Already watched', watched_movie_selections_path, class: "btn m-3" %>
      <%= link_to  'Favourites', favourites_movie_selections_path, class: "btn m-3" %>
    </div>
  </div>
</div>


<div class= "smallcard-space">
  <div class="smallcards">

    <% @movie_selections.each do |movie_selection| %>
    <div class= "smallcard-category relative">
      
      <%= link_to movie_path(movie_selection.movie) do %>
        <div class="smallcard-category relative" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path movie_selection.movie.poster.key %>)">
        </div>
      <% end %>

      <div class="absoluteeye">
      <%= link_to movie_selection_path(movie_selection, attribute: :watched), method: :put do %>
        <div class="EyeAnimation iconstyle" data-toggle="tooltip" data-placement="top" title="Add this to already watched"></div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/movie_selections/watched.html.erb
<div class="container">
  <!-- <h1>Already watched...</h1> -->
  <div class="row justify-content-center">
    <div class="div.col-md-6">
      <%= link_to 'Watchlist', movie_selections_path, class: "btn m-3 " %>
      <%= link_to  'Already watched', watched_movie_selections_path, class: "btn m-3 active-tab" %>
      <%= link_to  'Favourites', favourites_movie_selections_path, class: "btn m-3" %>
    </div>
  </div>
</div>


<div class= "smallcard-space">
  <div class="smallcards">

    <% @movie_selections.each do |movie_selection| %>
        <div class="smallcard-category relative" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path movie_selection.movie.poster.key %>)">

          <div class="absoluteheart">
            <%= link_to movie_selection_path(movie_selection, attribute: :favourite), method: :put do %>
              <div class="HeartAnimation iconstyle" data-toggle="tooltip" data-placement="top" title="Add this to your favourites"></div>
            <% end %>
          </div>
          <%= link_to movie_path(movie_selection.movie), class: "abs-link" do %>
          <% end %>
        </div>


    <% end %>
  </div>
</div>

app/views/movies/index.html.erb
 <div class="container">
  <div class="search-bar-header">
    <h1>Find your next <strong>favourite</strong> movie...</h1>

      <div class="positionleft">
        <%= form_tag movies_path, method: :get do %>
          <div class="search-bar d-flex" id="users-search">
            <%= text_field_tag :query,
              params[:query],
              class: "form-control index-bar" %>
            <%= submit_tag "Search", class: "btn ml-3 active-tab" %>
          </div>
        <% end %>
      </div>

  </div>

    <div class="platform container">
    <div class="platformfixed">
      <div class="btn-container btn-sticky">
        <% Movie.platform.values.each do |platform| %>
          <div class="logo">
            <%= link_to movies_path(platform: platform) do %>
              <span class="platform-btn mb-3"><%= image_tag "#{platform}.jpg", style: "border-radius: 5px", class: "icon-image #{'icon-show' if params[:platform] == platform }"%></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
      <div class="movie-list container">
        <div class= "card-space">
          <div class="cards">
            <% @movies.each do |movie| %>
              <%= link_to movie_path(movie) do %>
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path movie.poster.key %>)">
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/movies/show.html.erb
<style type="text/css">
  @keyframes load {
    0% { width: 0; }
    100% { width: <%= @movie.rating %>%; }
  }
</style>
<div class="container">

  <div class="show-info d-flex">

    <div class= mr-4>

      <div class="show-btn-container d-flex justify-content-around align-items-center">
        <!-- Add btn -->
        <div>
          <% if current_user.movies.include?(@movie) %>
            <p style="padding-top:15px">This movie is already in your Watchlist !</p>
          <% else %>
            <%= link_to 'Add to Watchlist', movie_movie_selections_path(@movie), method: :post, class: "btn m-3 active-tab" %>
          <% end %>
        </div>
        <!-- Add recommendation btn -->
        <div>
          <div class="btn m-3 active-tab" data-toggle="modal" data-target="#exampleModal">
            Recommend to a friend
          </div>
        </div>
      </div>

      <!-- poster -->
      <div class="show-poster d-flex">
        <%= image_tag @movie.poster, alt: "", class: "movie-poster-show" %>
      </div>
      <!-- poster -->
    </div>



    <div class="show-details">
      <h1 class="movie-title"> <%= @movie.title %> </h1>
      <br>
      <h4 class="movie-director"> <i class="fas fa-video"></i> <%=  @movie.director %> </h4>
      <p> <i class="fas fa-clock"></i> <%= @movie.runtime %> min </p>
      <p> <i class="fas fa-hourglass"></i> <%= @movie.year %> </p>
      <p> <%= @movie.description %> </p>


      <div class= "d-flex align-items-center">

        <% genres = @movie.genre.split(", ") %>
        <% genres.each do |genre| %>
          <p class="btn-gender"> <%= genre %> </p>
        <% end %>

        <%= link_to movies_path(platform: @movie.platform) do %>
          <span class="platform-btn m-3"><%= image_tag "#{@movie.platform}.jpg", style: "border-radius: 50%" %></span>
        <% end %>
      </div>


      <!-- progress bar -->
      <div class="chart">
          <div class="bar"></div>
          <span id="value1"><%= @movie.rating %></span>
      <br>
      </div>
      <!-- progress bar -->

      <!-- trailer -->
      <br>
      <% if @movie.youtube_id.present? %>
        <iframe width="560" height="315" src="<%= "https://www.youtube.com/embed/#{@movie.youtube_id}" %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <% end %>


    </div>
  </div>

</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">

    <div class="modal-content modal-recommend">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Recommend this movie to your friend</h5>
        <button type="button" class="close " data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body ">
        <%= simple_form_for [@movie, @recommendation], defaults: {input_html:{class: "form-control-recommend"}} do |f|%>
          <%= f.association :recommendee, value_method: :id, label_method: :first_name%>

          <%= f.submit class: "btn btn-reco" %>

        <% end %>
      </div>

  </div>
</div

app/views/pages/home.html.erb
<div class='position-relative'>
  <video autoplay muted loop src=<%= cl_video_path ENV["VIDEO_HOME"] %> type=“video/mp4” class="video-centre">
  </video>

    <div class="home-overlay">
      <h1>Take your seat...</h1>
      <%= link_to '...and discover the world of cinema', movies_path, class: "btn active-tab m-3" %>
    </div>
  </div>

app/views/recommendations/create.html.erb
<h1>Recommendations#create</h1>
<p>Find me in app/views/recommendations/create.html.erb</p>

app/views/recommendations/destroy.html.erb
<h1>Recommendations#destroy</h1>
<p>Find me in app/views/recommendations/destroy.html.erb</p>

app/views/recommendations/index.html.erb
<h1>Recommendations#index</h1>
<p>Find me in app/views/recommendations/index.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><%= notice %></span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= "no-margin-bottom" if current_page?(root_path) %>">
  <%= link_to movies_path, class: "navbar-brand" do %>
    <div class="d-flex align-items-center">
      <h1 style="color:#d8d8d8; font-size:42px; margin:0px; letter-spacing: 4px; margin-right:5px;"> FELLINI</h1>
      <%= image_tag "ocho-y-medio.png" %>
    </div>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "My watchlist", movie_selections_path, class: "nav-link" %>
        </li>
        <li class="nav-item relative">
          <%= link_to "Recommendations", "#", data:{toggle: "modal", target: "#recommendModal"}, class: "nav-link" %>
          <% if current_user.recommended.count > 0 %>
            <div class="badge" id='rec-badge'>
              <%= current_user.recommended.count %>
            </div>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">

          <div class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar" %>
            <% else %>
              <%= image_tag "https://www.italymagazine.com/sites/default/files/story/fellini.jpg", class: "avatar" %>
            <% end %>
          </div>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>

  </div>

</div>


<!-- Button trigger modal -->

<% if user_signed_in? %>
  <!-- Modal -->
  <div class="modal fade" id="recommendModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content tinder-content">
        <div class="modal-body">

  <!-- TINDER -->

          <div class="tinder">
            <div class="tinder--status">
              <i class="fa fa-remove"></i>
              <i class="fa fa-heart"></i>
            </div>

            <div class="tinder--cards">

                <% current_user.recommended.each do |recommendation| %>
                  <div class="tinder--card" data-url="<%= watch_api_v1_recommendation_url(recommendation) %>" data-destroy="<%= api_v1_recommendation_url(recommendation) %>">
                    <%= image_tag recommendation.movie.poster, alt: "", class: "tinder--img" %>
                    <h3><%= recommendation.movie.title %></h3>
                    <p><%= recommendation.movie.description %></p>
                    <p>Your friend <%= recommendation.user.first_name%> has recommended you this</p>
                    <%= cl_image_tag recommendation.user.photo.key, class: "avatar", alt: "alttext" %>
                  </div>
                <% end %>
                <% if current_user.recommended.empty? %>
                  <div class="tinder--card">
                    <img src="">
                    <h3>You don't have any recommended movies</h3>
                    <p>Try making some friends</p>
                  </div>
                <% end %>

            </div>

            <div class="tinder--buttons">
              <button id="nope"><i class="fa fa-times"></i></button>
              <button id="love"><i class="fas fa-eye"></i></button>
            </div>
          </div>

  <!-- END TINDER -->
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="friends-list d-flex">
    <div class="friends-header mb-1">
      <h3>Your friends...</h3>
        <% if @friends.any? %>
          <% @friends.each do |friend| %>
            <%= link_to user_path(friend), class: "friend-link" do  %>
              <%= cl_image_tag friend.photo.key, class: "friend-img m-1" %>
              <span class="friend-name">
                <%= friend.first_name %>
              </span>
            <% end %>
          <% end %>
        <% else %>
          <p>You haven't got any friends yet - Try searching below!</p>
        <% end %>
    </div>
  </div>

  <div class="search-bar-header">
    <h1>Find fellow movie lovers...</h1>
      <div>
        <%= form_tag users_path, method: :get do %>
          <div class="search-bar d-flex" id="user-search">
            <%= text_field_tag :query,
              params[:query],
              class: "user-form-control" %>
            <%= submit_tag "Search", class: "btn ml-3 active-tab" %>
          </div>
        <% end %>
      </div>
  </div>

  <div class="user-list d-flex">
    <% @users.each do |user| %>
      <div class="friend-card align-items-center d-flex m-3">
        <%= link_to user_path(user), class: 'f-col' do %>
          <%= cl_image_tag user.photo.key, class: "user-img" %>
          <div>
            <h3> <%= user.first_name %> <%= user.last_name %> </h3>
          </div>
        <% end %>
        <% if current_user.friends?(user) %>
          <%= link_to "Unfriend #{user.first_name}", friend_path(Friend.where(user: current_user, friend: user).or(Friend.where(user: user, friend: current_user)).first), method: :delete, class: "btn-friends m-1 active-tab"  %>
          <% else %>
          <%= link_to "Add #{user.first_name}" , user_friends_path(current_user, friend: user), method: :post, class: "btn-friends m-1 active-tab" %>
        <% end %>
       </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="d-flex flex-column align-items-center">
  <div class="box d-flex align-items-center px-5" style="width: 900px">
    <h1 class="mb-3"> <%= "#{@user.first_name} #{@user.last_name}" %> </h1>
    <%= cl_image_tag @user.photo.key, class: "avatar-large mb-3" %>
    <p> <%= @user.bio %> </p>
    <% unless current_user == @user %>
      <% if current_user.friends?(@user) %>
        <%= link_to "Unfriend #{@user.first_name}", friend_path(Friend.where(user: current_user, friend: @user).or(Friend.where(user: @user, friend: current_user)).first), method: :delete, class: "btn m-3 active-tab" %>
      <% else %>
        <%= link_to "Add #{@user.first_name}" , user_friends_path(current_user, friend: @user), method: :post, class: "btn m-3 active-tab" %>
      <% end %>
    <% end %>

  </div>
  <div>
    <div><h3> <%= @user.first_name %> recommended... </h3></div>
    <div class="d-flex">
      <% if @recommended_movies.any? %>
        <% @recommended_movies.each do |recommended_movie| %>
          <div class="smallcard-category f0 relative m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path recommended_movie.movie.poster.key %>)">
            <%= link_to user_path(recommended_movie.recommendee), class: "top-left" do  %>
              <%= cl_image_tag recommended_movie.recommendee.photo.key, class: "avatar", alt: "alttext" %>
            <% end %>
            <%= link_to movie_path(recommended_movie.movie), class: "abs-link" do  %>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <p> <%= @user.first_name %> hasn't made any recommendations yet.</p>
      <% end %>
    </div>
    <div><h3>Friends recommended... </h3>
      <div class="d-flex">
        <% if @suggested_movies.any? %>
          <% @suggested_movies.each do |suggested_movie| %>
            <div class="smallcard-category f0 relative m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path suggested_movie.movie.poster.key %>)">
              <%= link_to user_path(suggested_movie.user), class: "top-left" do  %>
                <%= cl_image_tag suggested_movie.user.photo.key, class: "avatar", alt: "alttext" %>
              <% end %>
              <%= link_to movie_path(suggested_movie.movie), class: "abs-link" do  %>
              <% end %>
            </div>
          <% end %>
        <% else %>
         <p> Be the first to recommend a movie to <%= @user.first_name %> <%= link_to "here", movies_path %>. </p>
        <% end %>
      </div>
    </div>
  </div>
</div>